coverage:
  status:
    project:
      default:
        target: 99%
        threshold: 1%
        informational: true

    patch:
      default:
        target: 99%
        threshold: 5%
        informational: true
