coverage:
  require_ci_to_pass: true

  status:
    project:
      default:
        target: 99%
        threshold: 99%
        informational: true

    patch:
      default:
        target: 99%
        threshold: 95%
        informational: true
